import { Centre } from '@/types';

export const MOCK_CENTRES: Centre[] = [
  {
    id: 'centre-14',
    name: 'Centre #14 — Hapur Central Mandi',
    code: 'UP-HPR-014',
    district: 'Hapur',
    state: 'Uttar Pradesh',
    distanceKm: 12.4,
    queueCount: 75,
    processingMetrics: {
      avgMinutesPerFarmer: 6.2,
      expectedMinutesPerFarmer: 4.0,
      deviationPercentage: 55, // +55% slow down
      activeCounters: 4,
      todayClearedCount: 142,
    },
    capacity: {
      currentLoad: 82,
      maxCapacity: 100,
      percentage: 82,
      truckSlotsOccupied: 28,
      truckSlotsTotal: 35,
    },
    status: 'congested',
    address: 'NH-9 Bypass Road, Near Railway Siding, Hapur, UP 245101',
    coordinates: { lat: 28.7306, lng: 77.7806 },
    openHours: '08:00 AM – 06:00 PM',
    facilities: ['Electronic Weighbridge (50T)', 'CCTV Surveillance', 'Kisan Canteen', 'Covered Shed (1200 sqm)', 'Moisture Tester'],
    recommendationScore: 68,
  },
  {
    id: 'centre-12',
    name: 'Centre #12 — Modinagar Agri Hub',
    code: 'UP-GZB-012',
    district: 'Ghaziabad',
    state: 'Uttar Pradesh',
    distanceKm: 18.2,
    queueCount: 20,
    processingMetrics: {
      avgMinutesPerFarmer: 3.8,
      expectedMinutesPerFarmer: 4.0,
      deviationPercentage: -5, // Running slightly faster
      activeCounters: 5,
      todayClearedCount: 186,
    },
    capacity: {
      currentLoad: 62,
      maxCapacity: 100,
      percentage: 62,
      truckSlotsOccupied: 16,
      truckSlotsTotal: 30,
    },
    status: 'optimal',
    address: 'Delhi-Meerut Expressway Link, Modinagar North, UP 201204',
    coordinates: { lat: 28.8355, lng: 77.5818 },
    openHours: '08:00 AM – 06:00 PM',
    facilities: ['Dual Weighbridges (60T)', 'Automated Moisture Analyzers', 'Air-cooled Farmer Rest Hall', 'Direct Rail Freight Siding'],
    recommendationScore: 94,
  },
  {
    id: 'centre-18',
    name: 'Centre #18 — Meerut North Krishi Upaj',
    code: 'UP-MRT-018',
    district: 'Meerut',
    state: 'Uttar Pradesh',
    distanceKm: 24.8,
    queueCount: 68,
    processingMetrics: {
      avgMinutesPerFarmer: 7.5,
      expectedMinutesPerFarmer: 4.5,
      deviationPercentage: 66,
      activeCounters: 3,
      todayClearedCount: 98,
    },
    capacity: {
      currentLoad: 94,
      maxCapacity: 100,
      percentage: 94,
      truckSlotsOccupied: 38,
      truckSlotsTotal: 40,
    },
    status: 'critical',
    address: 'Roorkee Road, Dorli, Meerut, UP 250001',
    coordinates: { lat: 29.0222, lng: 77.7125 },
    openHours: '08:30 AM – 05:30 PM',
    facilities: ['Weighbridge', 'Basic Rest Shed', 'Soil Testing Lab'],
    recommendationScore: 52,
  },
  {
    id: 'centre-07',
    name: 'Centre #07 — Bulandshahr Grain Complex',
    code: 'UP-BLS-007',
    district: 'Bulandshahr',
    state: 'Uttar Pradesh',
    distanceKm: 28.5,
    queueCount: 22,
    processingMetrics: {
      avgMinutesPerFarmer: 4.2,
      expectedMinutesPerFarmer: 4.5,
      deviationPercentage: -7,
      activeCounters: 4,
      todayClearedCount: 165,
    },
    capacity: {
      currentLoad: 52,
      maxCapacity: 100,
      percentage: 52,
      truckSlotsOccupied: 14,
      truckSlotsTotal: 30,
    },
    status: 'optimal',
    address: 'G.T. Road, Chola Crossing, Bulandshahr, UP 203001',
    coordinates: { lat: 28.4069, lng: 77.8498 },
    openHours: '08:00 AM – 06:00 PM',
    facilities: ['Electronic Weighbridge', 'Kisan Sahayata Kendra', 'Free Drinking Water & Tea', 'Solar Covered Yard'],
    recommendationScore: 88,
  },
  {
    id: 'centre-21',
    name: 'Centre #21 — Pilkhuwa Sub-Yard',
    code: 'UP-HPR-021',
    district: 'Hapur',
    state: 'Uttar Pradesh',
    distanceKm: 8.5,
    queueCount: 31,
    processingMetrics: {
      avgMinutesPerFarmer: 4.8,
      expectedMinutesPerFarmer: 4.0,
      deviationPercentage: 20,
      activeCounters: 3,
      todayClearedCount: 118,
    },
    capacity: {
      currentLoad: 76,
      maxCapacity: 100,
      percentage: 76,
      truckSlotsOccupied: 19,
      truckSlotsTotal: 25,
    },
    status: 'moderate',
    address: 'Railway Road, Mandi Samiti, Pilkhuwa, UP 245304',
    coordinates: { lat: 28.7118, lng: 77.6961 },
    openHours: '08:30 AM – 05:30 PM',
    facilities: ['Digital Weighbridge', 'Panchayat Seva Desk', 'Moisture Sensor Unit'],
    recommendationScore: 82,
  },
];
