import { DigitalTwinData } from '@/types';

export const MOCK_DIGITAL_TWIN: DigitalTwinData = {
  centreId: 'centre-14',
  centreName: 'Centre #14 — Hapur Central Mandi',
  updatedAt: '2026-04-12T10:32:00+05:30',
  farmersInside: 24,
  waitingFarmers: 37,
  currentlyProcessing: 4,
  completedToday: 142,
  avgWaitTimeMinutes: 42,
  todayCapacityPercentage: 82,
  weighingMachineStatus: 'AVAILABLE',
  staffAvailable: '8/10',
  queueDensity: 'MEDIUM',
  bottleneckZoneName: 'Document Verification & Moisture Testing',
  processingSpeedScore: 68,
  zones: [
    {
      id: 'zone-1',
      zoneType: 'entry',
      title: 'Gate #1 Entry & Staging Yard',
      subTitle: 'Vehicle ANPR & Token QR Check',
      iconName: 'Tractor',
      status: 'available',
      activeCount: 6,
      capacityLimit: 15,
      avgTimeMinutes: 2,
      staffAssigned: 2,
      equipmentStatus: 'RFID/QR Scanner Online (100% Signal)',
      notes: 'Tractors queuing in holding lanes A1-A3 without highway spillover.',
      isBottleneck: false,
    },
    {
      id: 'zone-2',
      zoneType: 'registration',
      title: 'Farmer Reception & Seating Hall',
      subTitle: 'Digital Token Validation & Token Display',
      iconName: 'UserCheck',
      status: 'available',
      activeCount: 8,
      capacityLimit: 50,
      avgTimeMinutes: 3,
      staffAssigned: 2,
      equipmentStatus: 'Digital Display Boards & Audio Chime Operational',
      notes: 'No overcrowding; 80% of farmers arriving just-in-time via SMS.',
      isBottleneck: false,
    },
    {
      id: 'zone-3',
      zoneType: 'verification',
      title: 'Verification & Moisture Testing',
      subTitle: 'Land Record Check & Sample Assay (FAQ Limit <12%)',
      iconName: 'ClipboardCheck',
      status: 'bottleneck', // 🔴 BOTTLENECK
      activeCount: 9,
      capacityLimit: 6,
      avgTimeMinutes: 6.2,
      staffAssigned: 1, // Only 1 officer instead of 2
      equipmentStatus: 'Sensor Lab 2 Calibration Lag — Manual Checking',
      notes: 'Operating 55% slower than benchmark. Delay propagates to downstream slots.',
      isBottleneck: true,
    },
    {
      id: 'zone-4',
      zoneType: 'weighing',
      title: 'Electronic Weighbridge (50T)',
      subTitle: 'Gross & Tare Weighment Recording',
      iconName: 'Scale',
      status: 'available', // 🟢 AVAILABLE
      activeCount: 2,
      capacityLimit: 4,
      avgTimeMinutes: 4,
      staffAssigned: 2,
      equipmentStatus: 'Load Cell Calibrated (Legal Metrology Valid till Nov 2026)',
      notes: 'Operating smoothly. Fast turnarounds once verification clears.',
      isBottleneck: false,
    },
    {
      id: 'zone-5',
      zoneType: 'procurement',
      title: 'Bagging, Tagging & Loading Bay',
      subTitle: 'Jute Bag Packaging (50kg) & Warehouse Stacking',
      iconName: 'PackageCheck',
      status: 'busy', // 🟡 BUSY
      activeCount: 14,
      capacityLimit: 20,
      avgTimeMinutes: 5,
      staffAssigned: 4,
      equipmentStatus: 'Conveyor Stacker #1 Operational, Stacker #2 Under Maintenance',
      notes: 'Continuous truck loading for FCI rail siding dispatch.',
      isBottleneck: false,
    },
    {
      id: 'zone-6',
      zoneType: 'exit',
      title: 'Discharge Gate & Weighment Slip Counter',
      subTitle: 'Instant Digitally Signed Receipt & DBT Trigger',
      iconName: 'DoorOpen',
      status: 'available',
      activeCount: 3,
      capacityLimit: 10,
      avgTimeMinutes: 2,
      staffAssigned: 1,
      equipmentStatus: 'Thermal Slip Printers & SMS DBT Notification Online',
      notes: 'Farmers exiting within 2 minutes of final weighing.',
      isBottleneck: false,
    },
  ],
};
