import { FairnessScore, FairnessAdjustment } from '@/types';

export const MOCK_FAIRNESS_SCORE: FairnessScore = {
  overallScore: 91,
  rating: 'EXCELLENT',
  centreAdherencePercentage: 88,
  protectedFarmersToday: 14,
  explainableAdjustmentsCount: 23,
  factors: [
    {
      id: 'f-1',
      name: 'Scheduled Slot Adherence',
      weight: 35,
      description: 'Farmers arriving on-time receive baseline sequential placement.',
      isConfigurable: true,
    },
    {
      id: 'f-2',
      name: 'Operational Delay Protection',
      weight: 25,
      description: 'Farmers delayed due to mandi equipment/counter lag are shielded from missed-slot penalties.',
      isConfigurable: false,
    },
    {
      id: 'f-3',
      name: 'Perishable Crop Freshness Window',
      weight: 15,
      description: 'Crops like high-moisture mustard or horticultural goods receive bounded priority.',
      isConfigurable: true,
    },
    {
      id: 'f-4',
      name: 'Special Assistance / Small Farmers',
      weight: 15,
      description: 'Marginal farmers (<2 acres) and senior citizens with manual transport.',
      isConfigurable: true,
    },
    {
      id: 'f-5',
      name: 'Missed Slot Safe Recovery',
      weight: 10,
      description: 'Graceful next-buffer allocation rather than full queue expulsion.',
      isConfigurable: true,
    },
  ],
};

export const MOCK_FAIRNESS_ADJUSTMENTS: FairnessAdjustment[] = [
  {
    tokenId: 'M-135',
    farmerName: 'Suresh Chandra Sharma',
    originalSlot: '10:00 AM',
    adjustedSlot: '10:00 AM',
    waitDurationMinutes: 32,
    status: 'On time',
    category: 'SPECIAL_ASSISTANCE',
    reason: 'On-time arrival. Processed in standard slot sequence.',
    fairnessProtectionApplied: false,
    scoreImpact: 'Neutral (Baseline)',
  },
  {
    tokenId: 'M-136',
    farmerName: 'Virender Tyagi',
    originalSlot: '10:05 AM',
    adjustedSlot: '10:18 AM',
    waitDurationMinutes: 41,
    status: 'Adjusted',
    category: 'FARMER_DELAYED_ARRIVAL',
    reason: 'Arrival delayed by farmer (tractor puncture). Slot adjustment applied according to policy without full cancellation.',
    fairnessProtectionApplied: false,
    scoreImpact: 'Adjusted (-2 positions)',
  },
  {
    tokenId: 'M-137',
    farmerName: 'Anandi Devi',
    originalSlot: '10:10 AM',
    adjustedSlot: '10:30 AM',
    waitDurationMinutes: 55,
    status: 'Protected',
    category: 'CENTRE_DELAY',
    reason: "Priority adjusted because: Farmer's original slot was affected by Centre #14 operational delay (Weighbridge calibration lag).",
    fairnessProtectionApplied: true,
    scoreImpact: 'Protected (+4 positions recovery)',
  },
  {
    tokenId: 'M-138',
    farmerName: 'Mohammad Shahid',
    originalSlot: '10:15 AM',
    adjustedSlot: '10:15 AM',
    waitDurationMinutes: 12,
    status: 'Normal',
    category: 'SPECIAL_ASSISTANCE',
    reason: 'Early staging arrival. Held in buffer zone until scheduled time.',
    fairnessProtectionApplied: false,
    scoreImpact: 'Standard Priority',
  },
  {
    tokenId: 'M-141',
    farmerName: 'Mukesh Kumar Meena',
    originalSlot: '10:30 AM',
    adjustedSlot: '10:45 AM',
    waitDurationMinutes: 38,
    status: 'Adjusted',
    category: 'FARMER_DELAYED_ARRIVAL',
    reason: 'Arrival delayed by farmer. Slot adjustment applied according to configured policy.',
    fairnessProtectionApplied: false,
    scoreImpact: 'Adjusted (+15 min buffer)',
  },
  {
    tokenId: 'M-142',
    farmerName: 'Ramesh Singh',
    originalSlot: '10:35 AM',
    adjustedSlot: '10:45 AM',
    waitDurationMinutes: 45,
    status: 'Protected',
    category: 'CENTRE_DELAY',
    reason: 'Target centre experienced 55% slowdown. Just-In-Time arrival time dynamically shifted to 10:45 AM so farmer avoided 70+ minutes of physical queueing.',
    fairnessProtectionApplied: true,
    scoreImpact: 'High Protection (Zero On-Site Wait)',
  },
];
