import { Slot, DynamicSlotAlert } from '@/types';

export const MOCK_SLOTS: Slot[] = [
  {
    id: 'slot-1',
    centreId: 'centre-14',
    date: '2026-04-12',
    startTime: '08:00 AM',
    endTime: '09:30 AM',
    capacity: 25,
    booked: 25,
    available: 0,
    utilizationPercent: 100,
    status: 'full',
    delayMinutes: 20,
  },
  {
    id: 'slot-2',
    centreId: 'centre-14',
    date: '2026-04-12',
    startTime: '09:30 AM',
    endTime: '11:00 AM',
    capacity: 25,
    booked: 25,
    available: 0,
    utilizationPercent: 100,
    status: 'delayed',
    delayMinutes: 45,
  },
  {
    id: 'slot-3',
    centreId: 'centre-14',
    date: '2026-04-12',
    startTime: '11:00 AM',
    endTime: '12:30 PM',
    capacity: 25,
    booked: 24,
    available: 1,
    utilizationPercent: 96,
    status: 'filling',
    delayMinutes: 60,
  },
  {
    id: 'slot-4',
    centreId: 'centre-14',
    date: '2026-04-12',
    startTime: '01:00 PM',
    endTime: '02:30 PM',
    capacity: 25,
    booked: 18,
    available: 7,
    utilizationPercent: 72,
    status: 'available',
    delayMinutes: 15,
  },
  {
    id: 'slot-5',
    centreId: 'centre-14',
    date: '2026-04-12',
    startTime: '02:30 PM',
    endTime: '04:00 PM',
    capacity: 25,
    booked: 12,
    available: 13,
    utilizationPercent: 48,
    status: 'available',
    delayMinutes: 0,
  },
  {
    id: 'slot-6',
    centreId: 'centre-14',
    date: '2026-04-12',
    startTime: '04:00 PM',
    endTime: '05:30 PM',
    capacity: 20,
    booked: 6,
    available: 14,
    utilizationPercent: 30,
    status: 'available',
    delayMinutes: 0,
  },
];

export const MOCK_DYNAMIC_SLOT_ALERT: DynamicSlotAlert = {
  centreId: 'centre-14',
  centreName: 'Centre #14 — Hapur Central Mandi',
  expectedMinutesPerFarmer: 4.0,
  currentMinutesPerFarmer: 6.2,
  delayPercentage: 55, // 55% slower
  affectedFarmersCount: 24,
  additionalWaitMinutes: 78, // 1h 18m
  recommendedAlternativeCentreId: 'centre-12',
  recommendedAlternativeCentreName: 'Centre #12 — Modinagar Agri Hub',
  alternativeDistanceKm: 14.0,
  alternativeQueueCount: 12,
  alternativeTotalMinutes: 48,
  options: [
    {
      id: 'reschedule',
      title: 'Option 1: Reschedule Affected Farmers',
      description: 'Automatically notify and offer rescheduled slots for tomorrow morning with priority token protection.',
      actionLabel: 'Reschedule Farmers',
    },
    {
      id: 'move_farmers',
      title: 'Option 2: Move 8 Farmers to Centre #12',
      description: 'Redirect the tail end of the batch to Modinagar Agri Hub (14 km away, queue: 12 farmers, 48 min wait).',
      actionLabel: 'Reallocate to Centre #12',
    },
    {
      id: 'extend_hours',
      title: 'Option 3: Extend Operating Hours (+2 Hours)',
      description: 'Keep mandi gates and weighbridge open until 08:00 PM with night-shift staff clearance.',
      actionLabel: 'Extend Hours to 8:00 PM',
    },
    {
      id: 'keep_current',
      title: 'Option 4: Keep Current Schedule with Alerts',
      description: 'Retain current schedule and broadcast dynamic delay alerts to incoming farmers via IVR/SMS.',
      actionLabel: 'Broadcast Delay Alerts',
    },
  ],
};
