import { FarmerProfile } from '@/types';

export const MOCK_FARMERS: FarmerProfile[] = [
  {
    id: 'farmer-001',
    name: 'Ramesh Singh',
    fatherName: 'Hariram Singh',
    mobile: '+91 98765 43210',
    aadhaarHash: 'XXXX-XXXX-8921',
    farmerIdNumber: 'UP-FARM-2026-8921',
    village: 'Bhatiyana',
    district: 'Hapur',
    state: 'Uttar Pradesh',
    address: 'House #42, Main Chauraha, Bhatiyana, Hapur, UP',
    totalLandAcres: 6.5,
    primaryCrops: ['Wheat', 'Mustard', 'Sugarcane'],
    bankAccountLinked: true,
    bankName: 'Punjab National Bank (A/C: *******4921)',
    kisanCreditCard: true,
    registeredDate: '2025-10-14',
  },
  {
    id: 'farmer-002',
    name: 'Balwinder Kaur',
    fatherName: 'Gurdev Singh',
    mobile: '+91 98140 11223',
    aadhaarHash: 'XXXX-XXXX-4190',
    farmerIdNumber: 'PB-FARM-2026-4190',
    village: 'Kotla',
    district: 'Patiala',
    state: 'Punjab',
    address: 'VPO Kotla, Tehsil Nabha, Patiala, Punjab',
    totalLandAcres: 12.0,
    primaryCrops: ['Wheat', 'Paddy'],
    bankAccountLinked: true,
    bankName: 'State Bank of India',
    kisanCreditCard: true,
    registeredDate: '2025-11-02',
  },
  {
    id: 'farmer-003',
    name: 'Suresh Chandra Sharma',
    fatherName: 'Devi Dayal',
    mobile: '+91 94123 55678',
    aadhaarHash: 'XXXX-XXXX-7312',
    farmerIdNumber: 'UP-FARM-2026-7312',
    village: 'Dhaulana',
    district: 'Hapur',
    state: 'Uttar Pradesh',
    address: 'Near Shiv Mandir, Dhaulana, UP',
    totalLandAcres: 4.2,
    primaryCrops: ['Wheat', 'Chana'],
    bankAccountLinked: true,
    bankName: 'Canara Bank',
    kisanCreditCard: false,
    registeredDate: '2025-12-10',
  },
  {
    id: 'farmer-004',
    name: 'Virender Tyagi',
    fatherName: 'Satya Prakash Tyagi',
    mobile: '+91 97190 44321',
    aadhaarHash: 'XXXX-XXXX-9844',
    farmerIdNumber: 'UP-FARM-2026-9844',
    village: 'Muradnagar Dehat',
    district: 'Ghaziabad',
    state: 'Uttar Pradesh',
    address: 'VPO Muradnagar, Ghaziabad, UP',
    totalLandAcres: 8.0,
    primaryCrops: ['Wheat', 'Paddy', 'Mustard'],
    bankAccountLinked: true,
    bankName: 'HDFC Bank',
    kisanCreditCard: true,
    registeredDate: '2026-01-05',
  },
  {
    id: 'farmer-005',
    name: 'Harpreet Dhillon',
    fatherName: 'Jagjit Singh',
    mobile: '+91 98722 33445',
    aadhaarHash: 'XXXX-XXXX-1029',
    farmerIdNumber: 'HR-FARM-2026-1029',
    village: 'Radaur',
    district: 'Yamunanagar',
    state: 'Haryana',
    address: 'Farm Plot 18, Radaur, Yamunanagar, HR',
    totalLandAcres: 15.5,
    primaryCrops: ['Wheat', 'Sugarcane'],
    bankAccountLinked: true,
    bankName: 'Axis Bank',
    kisanCreditCard: true,
    registeredDate: '2026-01-18',
  },
  {
    id: 'farmer-006',
    name: 'Mukesh Kumar Meena',
    mobile: '+91 94140 88776',
    aadhaarHash: 'XXXX-XXXX-5521',
    farmerIdNumber: 'RJ-FARM-2026-5521',
    village: 'Mahwa',
    district: 'Dausa',
    state: 'Rajasthan',
    address: 'Gram Mahwa, Dausa, RJ',
    totalLandAcres: 3.5,
    primaryCrops: ['Mustard', 'Bajra', 'Wheat'],
    bankAccountLinked: true,
    bankName: 'Bank of Baroda',
    kisanCreditCard: true,
    registeredDate: '2026-02-01',
  },
  {
    id: 'farmer-007',
    name: 'Kailash Patel',
    mobile: '+91 98260 41234',
    aadhaarHash: 'XXXX-XXXX-6612',
    farmerIdNumber: 'MP-FARM-2026-6612',
    village: 'Sehore Kalan',
    district: 'Sehore',
    state: 'Madhya Pradesh',
    address: 'Plot 7, Sehore Kalan, MP',
    totalLandAcres: 9.0,
    primaryCrops: ['Wheat', 'Soybean', 'Chana'],
    bankAccountLinked: true,
    bankName: 'State Bank of India',
    kisanCreditCard: true,
    registeredDate: '2026-02-14',
  },
  {
    id: 'farmer-008',
    name: 'Rajendra Prasad Yadav',
    mobile: '+91 99350 22334',
    aadhaarHash: 'XXXX-XXXX-3341',
    farmerIdNumber: 'UP-FARM-2026-3341',
    village: 'Chitrakoot Dehat',
    district: 'Banda',
    state: 'Uttar Pradesh',
    address: 'Near Canal Bridge, Banda, UP',
    totalLandAcres: 5.0,
    primaryCrops: ['Wheat', 'Gram'],
    bankAccountLinked: true,
    bankName: 'Union Bank of India',
    kisanCreditCard: false,
    registeredDate: '2026-02-20',
  },
  {
    id: 'farmer-009',
    name: 'Anandi Devi',
    mobile: '+91 96500 11998',
    aadhaarHash: 'XXXX-XXXX-9912',
    farmerIdNumber: 'UP-FARM-2026-9912',
    village: 'Garhmukteshwar Rural',
    district: 'Hapur',
    state: 'Uttar Pradesh',
    address: 'Ward 3, Garhmukteshwar, UP',
    totalLandAcres: 2.8,
    primaryCrops: ['Wheat', 'Mustard'],
    bankAccountLinked: true,
    bankName: 'Punjab National Bank',
    kisanCreditCard: true,
    registeredDate: '2026-02-28',
  },
  {
    id: 'farmer-010',
    name: 'Devender Saini',
    mobile: '+91 98960 77123',
    aadhaarHash: 'XXXX-XXXX-8823',
    farmerIdNumber: 'HR-FARM-2026-8823',
    village: 'Ladwa',
    district: 'Kurukshetra',
    state: 'Haryana',
    address: 'VPO Ladwa, Kurukshetra, HR',
    totalLandAcres: 7.2,
    primaryCrops: ['Wheat', 'Paddy', 'Sunflower'],
    bankAccountLinked: true,
    bankName: 'HDFC Bank',
    kisanCreditCard: true,
    registeredDate: '2026-03-01',
  },
  {
    id: 'farmer-011',
    name: 'Mohammad Shahid',
    mobile: '+91 98370 66554',
    aadhaarHash: 'XXXX-XXXX-4432',
    farmerIdNumber: 'UP-FARM-2026-4432',
    village: 'Simbhaoli',
    district: 'Hapur',
    state: 'Uttar Pradesh',
    address: 'Sugar Mill Colony, Simbhaoli, UP',
    totalLandAcres: 4.8,
    primaryCrops: ['Wheat', 'Sugarcane'],
    bankAccountLinked: true,
    bankName: 'Central Bank of India',
    kisanCreditCard: true,
    registeredDate: '2026-03-02',
  },
  {
    id: 'farmer-012',
    name: 'Prakash Rao Shinde',
    mobile: '+91 94220 99887',
    aadhaarHash: 'XXXX-XXXX-1178',
    farmerIdNumber: 'MH-FARM-2026-1178',
    village: 'Niphad',
    district: 'Nashik',
    state: 'Maharashtra',
    address: 'Post Niphad, Taluka Niphad, Nashik, MH',
    totalLandAcres: 8.5,
    primaryCrops: ['Wheat', 'Onion', 'Soybean'],
    bankAccountLinked: true,
    bankName: 'Bank of Maharashtra',
    kisanCreditCard: true,
    registeredDate: '2026-03-03',
  },
  {
    id: 'farmer-013',
    name: 'Babu Lal Verma',
    mobile: '+91 94133 22110',
    aadhaarHash: 'XXXX-XXXX-2244',
    farmerIdNumber: 'RJ-FARM-2026-2244',
    village: 'Kishangarh',
    district: 'Ajmer',
    state: 'Rajasthan',
    address: 'Near Old Bus Stand, Kishangarh, RJ',
    totalLandAcres: 5.5,
    primaryCrops: ['Wheat', 'Barley'],
    bankAccountLinked: true,
    bankName: 'State Bank of India',
    kisanCreditCard: false,
    registeredDate: '2026-03-04',
  },
  {
    id: 'farmer-014',
    name: 'Gurmeet Singh Brar',
    mobile: '+91 98150 44556',
    aadhaarHash: 'XXXX-XXXX-7788',
    farmerIdNumber: 'PB-FARM-2026-7788',
    village: 'Moga Rural',
    district: 'Moga',
    state: 'Punjab',
    address: 'VPO Kot Ise Khan, Moga, PB',
    totalLandAcres: 18.0,
    primaryCrops: ['Wheat', 'Paddy'],
    bankAccountLinked: true,
    bankName: 'Punjab National Bank',
    kisanCreditCard: true,
    registeredDate: '2026-03-05',
  },
  {
    id: 'farmer-015',
    name: 'Maheshwar Goswami',
    mobile: '+91 94520 11447',
    aadhaarHash: 'XXXX-XXXX-6699',
    farmerIdNumber: 'UP-FARM-2026-6699',
    village: 'Khekra',
    district: 'Baghpat',
    state: 'Uttar Pradesh',
    address: 'Gram Khekra, Baghpat, UP',
    totalLandAcres: 3.2,
    primaryCrops: ['Wheat', 'Mustard'],
    bankAccountLinked: true,
    bankName: 'Indian Bank',
    kisanCreditCard: true,
    registeredDate: '2026-03-06',
  },
  {
    id: 'farmer-016',
    name: 'Sunita Bai Chouhan',
    mobile: '+91 98270 33221',
    aadhaarHash: 'XXXX-XXXX-3388',
    farmerIdNumber: 'MP-FARM-2026-3388',
    village: 'Vidisha Dehat',
    district: 'Vidisha',
    state: 'Madhya Pradesh',
    address: 'Gram Gulabganj, Vidisha, MP',
    totalLandAcres: 4.0,
    primaryCrops: ['Wheat', 'Chana'],
    bankAccountLinked: true,
    bankName: 'State Bank of India',
    kisanCreditCard: true,
    registeredDate: '2026-03-07',
  },
  {
    id: 'farmer-017',
    name: 'Ajit Kumar Jha',
    mobile: '+91 94312 88990',
    aadhaarHash: 'XXXX-XXXX-5566',
    farmerIdNumber: 'BR-FARM-2026-5566',
    village: 'Purnia East',
    district: 'Purnia',
    state: 'Bihar',
    address: 'Ward 12, Purnia East, BR',
    totalLandAcres: 6.0,
    primaryCrops: ['Maize', 'Wheat', 'Paddy'],
    bankAccountLinked: true,
    bankName: 'UCO Bank',
    kisanCreditCard: false,
    registeredDate: '2026-03-08',
  },
  {
    id: 'farmer-018',
    name: 'Satish Narang',
    mobile: '+91 98965 12345',
    aadhaarHash: 'XXXX-XXXX-9900',
    farmerIdNumber: 'HR-FARM-2026-9900',
    village: 'Karnal Cantt Rural',
    district: 'Karnal',
    state: 'Haryana',
    address: 'Sector 32 Bypass, Karnal, HR',
    totalLandAcres: 11.0,
    primaryCrops: ['Wheat', 'Basmati Rice'],
    bankAccountLinked: true,
    bankName: 'ICICI Bank',
    kisanCreditCard: true,
    registeredDate: '2026-03-09',
  },
  {
    id: 'farmer-019',
    name: 'Trilochan Mohapatra',
    mobile: '+91 94370 55443',
    aadhaarHash: 'XXXX-XXXX-8811',
    farmerIdNumber: 'OD-FARM-2026-8811',
    village: 'Bhadrak Sadar',
    district: 'Bhadrak',
    state: 'Odisha',
    address: 'Post Randia, Bhadrak, OD',
    totalLandAcres: 4.5,
    primaryCrops: ['Paddy', 'Pulses'],
    bankAccountLinked: true,
    bankName: 'Indian Overseas Bank',
    kisanCreditCard: true,
    registeredDate: '2026-03-10',
  },
  {
    id: 'farmer-020',
    name: 'Chaudhary Vikramaditya',
    mobile: '+91 97600 77889',
    aadhaarHash: 'XXXX-XXXX-4422',
    farmerIdNumber: 'UP-FARM-2026-4422',
    village: 'Babugarh',
    district: 'Hapur',
    state: 'Uttar Pradesh',
    address: 'Babugarh Cantt Rural, Hapur, UP',
    totalLandAcres: 9.8,
    primaryCrops: ['Wheat', 'Mustard'],
    bankAccountLinked: true,
    bankName: 'Punjab National Bank',
    kisanCreditCard: true,
    registeredDate: '2026-03-11',
  },
  {
    id: 'farmer-021',
    name: 'Kishan Lal Mehra',
    mobile: '+91 94142 99001',
    aadhaarHash: 'XXXX-XXXX-3311',
    farmerIdNumber: 'RJ-FARM-2026-3311',
    village: 'Alwar Rural',
    district: 'Alwar',
    state: 'Rajasthan',
    address: 'VPO Mia, Alwar, RJ',
    totalLandAcres: 5.2,
    primaryCrops: ['Wheat', 'Mustard'],
    bankAccountLinked: true,
    bankName: 'Punjab National Bank',
    kisanCreditCard: true,
    registeredDate: '2026-03-12',
  },
];
