import { ProcurementRecord } from '@/types';

export const MOCK_PROCUREMENT_RECORD: ProcurementRecord = {
  id: 'proc-2026-8921',
  procurementId: 'UP-MSP-2026-WHT-0489',
  tokenId: 'M-142',
  farmerId: 'farmer-001',
  farmerName: 'Ramesh Singh',
  centreId: 'centre-14',
  centreName: 'Centre #14 — Hapur Central Mandi',
  date: '2026-04-12',
  crop: 'Wheat (FAQ Grade)',
  quantityQuintals: 25.0, // 2500 kg
  moisturePercent: 11.2, // Under 12% threshold
  grade: 'FAQ (Fair Average Quality)',
  mspRatePerQuintal: 2275, // Govt MSP for Wheat 2025-26
  grossAmount: 56875,
  deductions: 0,
  netPayableAmount: 56875,
  weighmentSlipNumber: 'WB-HPR-2026-9941',
  currentStage: 'WEIGHING',
  stages: [
    {
      stage: 'REGISTRATION',
      label: '1. Farmer Registration',
      description: 'Farmer profile and Aadhaar/Land record verified via PM-Kisan registry.',
      completed: true,
      active: false,
      timestamp: '2025-10-14 11:30 AM',
      officerName: 'Portal Auto-verified',
    },
    {
      stage: 'SLOT_BOOKED',
      label: '2. Slot Booked',
      description: 'Slot confirmed for 10:00 AM – 11:30 AM with Digital Token M-142 issued.',
      completed: true,
      active: false,
      timestamp: 'Today, 08:15 AM',
      officerName: 'MandiSetu Dynamic Scheduler',
    },
    {
      stage: 'ARRIVED',
      label: '3. Arrived at Mandi',
      description: 'Vehicle ANPR registered at Gate #1. Just-In-Time arrival executed.',
      completed: true,
      active: false,
      timestamp: 'Today, 10:42 AM',
      officerName: 'Security Gate In-Charge',
    },
    {
      stage: 'VERIFICATION',
      label: '4. Document & Quality Assay',
      description: 'Moisture assay: 11.2% (Accepted). Land ownership quota: 25 Qtl verified.',
      completed: true,
      active: false,
      timestamp: 'Today, 10:52 AM',
      officerName: 'Anil Kumar (Assay Officer)',
    },
    {
      stage: 'WEIGHING',
      label: '5. Electronic Weighing',
      description: 'Tractor Gross Weight: 4,820 kg. Unloading onto Bagging Conveyor.',
      completed: false,
      active: true,
      timestamp: 'In Progress (Started 10:56 AM)',
      officerName: 'Vikram Mehta (Weighbridge Operator)',
    },
    {
      stage: 'PROCUREMENT_COMPLETE',
      label: '6. Procurement Complete',
      description: 'Weighment slip signed and lot transferred to Food Corporation of India (FCI) buffer.',
      completed: false,
      active: false,
    },
    {
      stage: 'PAYMENT_PROCESSING',
      label: '7. Payment Processing',
      description: 'Direct Benefit Transfer (DBT) invoice generated and sent to PFMS gateway.',
      completed: false,
      active: false,
    },
    {
      stage: 'PAYMENT_COMPLETED',
      label: '8. Payment Completed',
      description: 'Direct credit into farmer’s verified bank account via Aadhaar Payment Bridge.',
      completed: false,
      active: false,
    },
  ],
};
