import { QueueEntry, LiveQueueState } from '@/types';

export const MOCK_LIVE_QUEUE_STATE: LiveQueueState = {
  currentServingToken: 'M-134',
  currentServingFarmer: 'Rajendra Prasad Yadav (Wheat - 32 Qtl)',
  activeCounterCount: 4,
  totalWaiting: 37,
  avgServiceMinutes: 6.2,
  predictedClearanceHours: 3.7,
  centreDelayDetected: true,
  centreDelayMinutes: 78, // 1h 18m
};

export const MOCK_QUEUE_ENTRIES: QueueEntry[] = [
  {
    id: 'q-134',
    tokenId: 'M-134',
    farmerId: 'farmer-008',
    farmerName: 'Rajendra Prasad Yadav',
    mobile: '+91 99350 22334',
    crop: 'Wheat',
    quantityKg: 3200,
    slotTime: '09:00 AM',
    estimatedArrival: '09:20 AM (Arrived)',
    estimatedServiceTime: '09:40 AM',
    farmersAhead: 0,
    estimatedWaitMinutes: 0,
    status: 'serving',
    centreId: 'centre-14',
    counterNumber: 1,
    fairnessScore: 98,
    isProtected: false,
  },
  {
    id: 'q-135',
    tokenId: 'M-135',
    farmerId: 'farmer-003',
    farmerName: 'Suresh Chandra Sharma',
    mobile: '+91 94123 55678',
    crop: 'Chana',
    quantityKg: 1800,
    slotTime: '10:00 AM',
    estimatedArrival: '09:50 AM',
    estimatedServiceTime: '10:06 AM',
    farmersAhead: 1,
    estimatedWaitMinutes: 6,
    status: 'approaching',
    centreId: 'centre-14',
    counterNumber: 2,
    fairnessScore: 94,
    isProtected: false,
  },
  {
    id: 'q-136',
    tokenId: 'M-136',
    farmerId: 'farmer-004',
    farmerName: 'Virender Tyagi',
    mobile: '+91 97190 44321',
    crop: 'Wheat',
    quantityKg: 4000,
    slotTime: '10:05 AM',
    estimatedArrival: '10:15 AM',
    estimatedServiceTime: '10:18 AM',
    farmersAhead: 2,
    estimatedWaitMinutes: 18,
    status: 'delayed',
    centreId: 'centre-14',
    counterNumber: 3,
    fairnessScore: 89,
    delayReason: 'Arrival delayed by farmer. Slot adjustment applied according to policy.',
    isProtected: false,
  },
  {
    id: 'q-137',
    tokenId: 'M-137',
    farmerId: 'farmer-009',
    farmerName: 'Anandi Devi',
    mobile: '+91 96500 11998',
    crop: 'Mustard',
    quantityKg: 1500,
    slotTime: '10:10 AM',
    estimatedArrival: '10:25 AM',
    estimatedServiceTime: '10:30 AM',
    farmersAhead: 3,
    estimatedWaitMinutes: 30,
    status: 'on_track',
    centreId: 'centre-14',
    counterNumber: 4,
    fairnessScore: 99,
    delayReason: "Farmer's original slot was affected by Centre #14 operational delay. Protected against missed-slot penalty.",
    isProtected: true,
  },
  {
    id: 'q-138',
    tokenId: 'M-138',
    farmerId: 'farmer-011',
    farmerName: 'Mohammad Shahid',
    mobile: '+91 98370 66554',
    crop: 'Wheat',
    quantityKg: 2800,
    slotTime: '10:15 AM',
    estimatedArrival: '10:30 AM',
    estimatedServiceTime: '10:36 AM',
    farmersAhead: 4,
    estimatedWaitMinutes: 36,
    status: 'waiting',
    centreId: 'centre-14',
    fairnessScore: 92,
    isProtected: false,
  },
  {
    id: 'q-139',
    tokenId: 'M-139',
    farmerId: 'farmer-015',
    farmerName: 'Maheshwar Goswami',
    mobile: '+91 94520 11447',
    crop: 'Wheat',
    quantityKg: 2200,
    slotTime: '10:20 AM',
    estimatedArrival: '10:35 AM',
    estimatedServiceTime: '10:42 AM',
    farmersAhead: 5,
    estimatedWaitMinutes: 42,
    status: 'waiting',
    centreId: 'centre-14',
    fairnessScore: 93,
    isProtected: false,
  },
  {
    id: 'q-140',
    tokenId: 'M-140',
    farmerId: 'farmer-020',
    farmerName: 'Chaudhary Vikramaditya',
    mobile: '+91 97600 77889',
    crop: 'Wheat',
    quantityKg: 5000,
    slotTime: '10:25 AM',
    estimatedArrival: '10:40 AM',
    estimatedServiceTime: '10:48 AM',
    farmersAhead: 6,
    estimatedWaitMinutes: 48,
    status: 'waiting',
    centreId: 'centre-14',
    fairnessScore: 95,
    isProtected: false,
  },
  {
    id: 'q-141',
    tokenId: 'M-141',
    farmerId: 'farmer-006',
    farmerName: 'Mukesh Kumar Meena',
    mobile: '+91 94140 88776',
    crop: 'Mustard',
    quantityKg: 1900,
    slotTime: '10:30 AM',
    estimatedArrival: '10:42 AM',
    estimatedServiceTime: '10:54 AM',
    farmersAhead: 7,
    estimatedWaitMinutes: 54,
    status: 'waiting',
    centreId: 'centre-14',
    fairnessScore: 90,
    isProtected: false,
  },
  {
    id: 'q-142',
    tokenId: 'M-142',
    farmerId: 'farmer-001',
    farmerName: 'Ramesh Singh (YOU)',
    mobile: '+91 98765 43210',
    crop: 'Wheat',
    quantityKg: 2500,
    slotTime: '10:35 AM',
    estimatedArrival: '10:45 AM (Depart Now)',
    estimatedServiceTime: '11:00 AM',
    farmersAhead: 8,
    estimatedWaitMinutes: 45,
    status: 'on_track',
    centreId: 'centre-14',
    fairnessScore: 96,
    isProtected: true,
  },
  {
    id: 'q-143',
    tokenId: 'M-143',
    farmerId: 'farmer-010',
    farmerName: 'Devender Saini',
    mobile: '+91 98960 77123',
    crop: 'Sunflower',
    quantityKg: 1200,
    slotTime: '10:40 AM',
    estimatedArrival: '11:00 AM',
    estimatedServiceTime: '11:06 AM',
    farmersAhead: 9,
    estimatedWaitMinutes: 52,
    status: 'waiting',
    centreId: 'centre-14',
    fairnessScore: 91,
    isProtected: false,
  },
  {
    id: 'q-144',
    tokenId: 'M-144',
    farmerId: 'farmer-018',
    farmerName: 'Satish Narang',
    mobile: '+91 98965 12345',
    crop: 'Wheat',
    quantityKg: 3500,
    slotTime: '10:45 AM',
    estimatedArrival: '11:08 AM',
    estimatedServiceTime: '11:12 AM',
    farmersAhead: 10,
    estimatedWaitMinutes: 58,
    status: 'waiting',
    centreId: 'centre-14',
    fairnessScore: 90,
    isProtected: false,
  },
];
