/**
 * Broker entity — maps 1:1 to the existing PostgreSQL `brokers` table.
 *
 *   id          int4         PRIMARY KEY (generated by the database)
 *   user_id     uuid         (UUID string — never a number)
 *   created_at  timestamptz  (set by the database)
 *
 * The backend has no ORM installed (services use plain `pg`), so this is a
 * plain TypeScript mapping rather than an ORM decorator class. No other
 * columns exist or are invented.
 */

export const BROKERS_TABLE = 'brokers';
export const BROKER_COLUMNS = 'id, user_id, created_at';

/** Row exactly as returned by `pg` from the `brokers` table. */
export interface BrokerRow {
  id: number; // int4
  user_id: string; // uuid
  created_at: Date; // timestamptz (pg returns a JS Date)
}

/** Broker as exposed by the API (camelCase, like the rest of the project). */
export interface Broker {
  id: number;
  userId: string;
  createdAt: string; // ISO-8601
}

export function toBroker(row: BrokerRow): Broker {
  return {
    id: row.id,
    userId: row.user_id,
    createdAt: row.created_at instanceof Date ? row.created_at.toISOString() : String(row.created_at),
  };
}
